version: "2"

services:
    apigateway:
        image: jcdemo/apigateway
        build: apigateway
        environment:
            - APP_URL=http://railsapp:3000
        ports:
            - "7373:5000"
